package com.farizma.truthdare;

public class Values {

    String[] truths = new String[]{
            "What is one thing you pretend to understand at work but actually do not?",
            "Have you ever stalked a colleague on social media?",
            "What is your most embarrassing office moment?",
            "Who in this room do you trust the least and why?",
            "Have you ever lied in a meeting to save yourself?",
            "What is the pettiest reason you have ever been annoyed at someone?",
            "What is your most useless hidden talent?",
            "What is the weirdest excuse you have used to avoid a call?",
            "What is one habit you know annoys people but you still do?",
            "Have you ever laughed in a serious situation?",
            "What is your biggest productivity lie?",
            "Who here would survive a zombie apocalypse first?",
            "What is one thing on your bucket list you have still not done?",
            "What is a harmless rumor about you that you secretly enjoy?",
            "Have you ever sent a message to the wrong person?",
            "What is one app you waste too much time on?",
            "What is the boldest thing you have done on impulse?",
            "Which colleague would you swap jobs with for a day?",
            "What is the most awkward compliment you have received?",
            "What is one thing you regret buying recently?",
            "Have you ever pretended to be busy to avoid helping someone?",
            "What is your most dramatic overreaction ever?",
            "What is one thing you are secretly competitive about?",
            "If your search history was shown right now, what would be most embarrassing?",
            "What is one social situation that makes you instantly uncomfortable?",
            "What is the funniest misunderstanding you have been part of?",
            "Have you ever judged someone and later realized you were wrong?",
            "What is one truth about yourself people are usually surprised by?",
            "What is the longest you have gone without checking your phone?",
            "What is one promise you made but never kept?"
    };

    String[] dares = new String[]{
            "Send a funny message to a random contact.",
            "Speak in a fake accent for the next 2 rounds.",
            "Do your boss impression for 30 seconds.",
            "Let someone else choose your next Instagram caption.",
            "Call a friend and say \"I need advice\" then hang up.",
            "Pitch a random object in this room like a startup idea.",
            "Do 15 squats while counting dramatically.",
            "Sing the chorus of your favorite song using only \"la la\".",
            "Walk like a runway model for 20 seconds.",
            "Set your phone wallpaper to a funny emoji for one hour.",
            "Do your best motivational speech for the group.",
            "Speak only in questions until your next turn.",
            "Pretend you are giving a weather report about this room.",
            "Act like a news anchor and report the latest snack update.",
            "Let the group rename you for the next two rounds.",
            "Read your last sent text in your most serious voice.",
            "Do a one-minute silent dance performance.",
            "Imitate your own laugh in slow motion.",
            "Take a dramatic selfie and show everyone.",
            "Invent a handshake and teach it to the group.",
            "Talk like a robot until your next turn.",
            "Tell a joke and commit fully even if nobody laughs.",
            "Give a 10-second ad for water as if it is a luxury product.",
            "Balance a book on your head for 20 seconds.",
            "Compliment everyone in the room in one sentence each.",
            "Pretend to accept an award for best snack eater.",
            "Do your best movie villain voice for 30 seconds.",
            "Make up a slogan for each person in the room.",
            "Hum a song until someone guesses it.",
            "Pose like a statue until the next player finishes their turn."
    };
}
